services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cvprojects_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cvprojects_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  tailwind:
    image: node:20-alpine
    container_name: cvprojects_tailwind
    working_dir: /workspace
    command: sh -c "npm install && npm run tw:watch"
    volumes:
      - ./:/workspace
      - tailwind_node_modules:/workspace/node_modules
    restart: unless-stopped

volumes:
  tailwind_node_modules:
  redis_data:
